name: Bug Report
description: Report unexpected behavior or visual issues in the application.
title: "[Bug]: "
labels: [bug]

body:
    - type: markdown
      attributes:
        value: |
            ## 🐞 Bug Report

            Thanks for reporting a bug! Please fill out the details below.

            - **Server Log Files:**
            These are located inside each cluster folder, typically under:
            `<Cluster Folder>/Master/server_log.txt` and `<Cluster Folder>/Caves/server_log.txt`

            Please attach these logs in the section below.

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: "Provide a clear and concise description of the bug."
          placeholder: "A clear and concise description of what the bug is."
      validations:
          required: true

    - type: textarea
      id: steps_to_reproduce
      attributes:
          label: Steps to Reproduce
          description: "List the steps to reproduce the bug."
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
      validations:
          required: true

    - type: textarea
      id: applogs
      attributes:
        label: App Logs
        description: |
          This field may have been auto-filled based on available data.
        placeholder: |
          Please copy and paste the log content from `appdata/logs/applog.txt` into this field.
        render: shell